name: To Deploy App Registration using GitHub Actions

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  
  
jobs:
    terraform:
        runs-on: ubuntu-latest
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}

        steps:
        - name: Checkout code
          uses: actions/checkout@v4 

        - name: Set up Terraform
          uses: hashicorp/setup-terraform@v3 

        - name: Terraform Init & Apply
          run: |
            terraform init
            terraform apply -auto-approve
            
                
